[package]
name = "benchtrees"
version = "0.1.0"
authors = ["Shane Pearman <spearman@gitlab.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slab_tree = "0.2.*"
id_tree = "1.*"
ego-tree = "0.6.*"
rand = "0.7.*"
